# tmux source-file ~/.config/tmux/tmux.conf

# Inspiration: https://github.com/gpakosz/.tmux
set -g default-terminal "screen-256color"

# `ESC` or `CTRL + [` is delayed for around 1 second
set-option -sg escape-time 0 

# VIM binding for pane navigation
# -r: This flag is for repeating

bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

set -g mouse on
